// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DefaultSuiteTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void registnewuser()
    {
        driver.Navigate().GoToUrl("https://guest:welcome2qauto@qauto.forstudy.space/");
        driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
        driver.FindElement(By.CssSelector(".hero-descriptor_btn")).Click();
        driver.FindElement(By.Id("signupName")).Click();
        driver.FindElement(By.Id("signupName")).SendKeys("Vlados");
        driver.FindElement(By.Id("signupLastName")).Click();
        driver.FindElement(By.Id("signupLastName")).SendKeys("Test");
        driver.FindElement(By.Id("signupEmail")).Click();
        driver.FindElement(By.Id("signupEmail")).SendKeys("vladostest@gmail.com");
        driver.FindElement(By.Id("signupPassword")).SendKeys("Qwerty12");
        driver.FindElement(By.Id("signupRepeatPassword")).SendKeys("Qwerty12");
        driver.FindElement(By.XPath("//button[@class=\'btn btn-primary\']")).Click();
        {
            WebDriverWait wait = new WebDriverWait(driver, System.TimeSpan.FromSeconds(10));
            wait.Until(driver => driver.FindElements(By.XPath("//*[@id=\'userNavDropdown\']")).Count > 0);
        }
        var elements = driver.FindElements(By.XPath("//*[@id=\'userNavDropdown\']"));
        Assert.True(elements.Count > 0);

    }
    [Test]
    public void AddCar()
    {

        driver.Navigate().GoToUrl("https://guest:welcome2qauto@qauto.forstudy.space/");
        driver.FindElement(By.CssSelector(".header_signin")).Click();
        driver.FindElement(By.Id("signinEmail")).Click();
        driver.FindElement(By.Id("signinEmail")).SendKeys("vladostest@gmail.com");
        driver.FindElement(By.Id("signinPassword")).Click();
        driver.FindElement(By.Id("signinPassword")).SendKeys("Qwerty12");
        driver.FindElement(By.XPath("//button[text()='Login']")).Click();
        WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.Until(driver => driver.FindElement(By.XPath("//button[text()='Add car']"))).Click();
        wait.Until(driver => driver.FindElement(By.Id("addCarBrand"))).Click();
        wait.Until(driver => driver.FindElement(By.XPath("//option[text()='Ford']"))).Click();
        wait.Until(driver => driver.FindElement(By.XPath("//option[. = 'TT']"))).Click();
       driver.FindElement(By.Id("addCarMileage")).Click();
       driver.FindElement(By.Id("addCarMileage")).SendKeys("150");
       driver.FindElement(By.CssSelector(".modal-footer > .btn-primary")).Click();
    }
    [Test]
    public void VerifyProfileInformation()
    {
        driver.Navigate().GoToUrl("https://guest:welcome2qauto@qauto.forstudy.space/");
        driver.FindElement(By.CssSelector(".header_signin")).Click();
        driver.FindElement(By.Id("signinEmail")).Click();
        driver.FindElement(By.Id("signinEmail")).SendKeys("vladostest@gmail.com");
        driver.FindElement(By.Id("signinPassword")).Click();
        driver.FindElement(By.Id("signinPassword")).SendKeys("Qwerty12");
        driver.FindElement(By.XPath("//button[text()='Login']")).Click();

        WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.Until(driver => driver.FindElement(By.Id("userNavDropdown"))).Click();
        wait.Until(driver => driver.FindElement(By.XPath("//a[text()='Profile']"))).Click(); 
        Thread.Sleep(2000);    
        IWebElement editProfileButton = wait.Until(driver => driver.FindElement(By.XPath("//button[text()='Edit profile']")));
        IJavaScriptExecutor js = (IJavaScriptExecutor)driver;
        js.ExecuteScript("arguments[0].click();", editProfileButton);      
        Thread.Sleep(2000);
        driver.FindElement(By.Id("editProfileName")).Click();
        driver.FindElement(By.Id("editProfileLastName")).Click();
        string profileName = wait.Until(driver => driver.FindElement(By.Id("editProfileName"))).GetAttribute("value");
        string profileLastName = wait.Until(driver => driver.FindElement(By.Id("editProfileLastName"))).GetAttribute("value");
        Assert.AreEqual("Vlados", profileName, "Ім'я не відповідає очікуваному значенню");
        Console.WriteLine("Actual profileName: " + profileName);
        Assert.AreEqual("Test", profileLastName, "Прізвище не відповідає очікуваному значенню");
        Console.WriteLine("Actual profileName: " + profileLastName);
    }
    [Test]
    public void Addexpenses()
    {
        driver.Navigate().GoToUrl("https://guest:welcome2qauto@qauto.forstudy.space/");
        driver.FindElement(By.CssSelector(".header_signin")).Click();
        driver.FindElement(By.Id("signinEmail")).Click();
        driver.FindElement(By.Id("signinEmail")).SendKeys("vladostest@gmail.com");
        driver.FindElement(By.Id("signinPassword")).Click();
        driver.FindElement(By.Id("signinPassword")).SendKeys("Qwerty12");
        driver.FindElement(By.XPath("//button[text()='Login']")).Click();
        WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.Until(driver => driver.FindElement(By.CssSelector(".car-item:nth-child(1) .car_add-expense"))).Click();
        wait.Until(driver => driver.FindElement(By.Id("addExpenseLiters"))).Click();
        wait.Until(driver => driver.FindElement(By.Id("addExpenseLiters"))).Click();
        wait.Until(driver => driver.FindElement(By.Id("addExpenseLiters"))).SendKeys("12");
        wait.Until(driver => driver.FindElement(By.Id("addExpenseTotalCost"))).Click();
        wait.Until(driver => driver.FindElement(By.Id("addExpenseTotalCost"))).SendKeys("5");
        wait.Until(driver => driver.FindElement(By.Id("addExpenseMileage"))).Click();
        wait.Until(driver => driver.FindElement(By.Id("addExpenseMileage"))).SendKeys("155");
        wait.Until(driver => driver.FindElement(By.CssSelector(".modal-footer > .btn-primary"))).Click();
    }
    [Test]
    public void deleteuser()
    {
        driver.Navigate().GoToUrl("https://guest:welcome2qauto@qauto.forstudy.space/");
        driver.FindElement(By.CssSelector(".header_signin")).Click();
        driver.FindElement(By.Id("signinEmail")).Click();
        driver.FindElement(By.Id("signinEmail")).SendKeys("vladostest@gmail.com");
        driver.FindElement(By.Id("signinPassword")).Click();
        driver.FindElement(By.Id("signinPassword")).SendKeys("Qwerty12");
        driver.FindElement(By.XPath("//button[text()='Login']")).Click();
        WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.Until(driver => driver.FindElement(By.Id("userNavDropdown"))).Click();
        wait.Until(driver => driver.FindElement(By.XPath("//a[text()='Settings']"))).Click();
        driver.FindElement(By.CssSelector(".btn-danger-bg")).Click();
        driver.FindElement(By.CssSelector(".btn-danger")).Click();
    }
}

